### PR TITLE
Fixes #45 - training queue waiting times

### LINKED ISSUE #45: Training queue waiting time showing as "Unknown" when greater than 30 days

### PR DESCRIPTION
**Pull request by xkeels**
Fixes #45. Behaviour was caused by relativeTime function returning "Unknown" if the number of days was greater than the maximum (30 days). This PR sets the maximum to Infinity. Having the function return "weeks", "months" or "years" seems less helpful for list tracking purposes.

### CODE REVIEW

**Review by c0repwn3r — CHANGES_REQUESTED** [review]
Can you add this up to days, months, and years? I feel like that will be more versatile than stalling out at days.

**Comment by xkeels** [comment]
I think for the purposes of the training queue, maxing out at days is more helpful, as waiting lists in some divisions can last over a year. For ATC staff trying to see how quickly a waiting list is moving, seeing several students waiting for "1 year" isn't particularly useful, whereas seeing the exact number of days allows this kind of analysis without needing to export data from Hayya's database.

I have added a new parameter to the relativeTime function which allows specification of a maximum unit, so allows flexibility where the function is used in other areas. I have maxed it out at "days" on the training queues and "hours" on the online users view.

**Comment by c0repwn3r** [comment]
Ok.. that sounds good to me.

**Review by c0repwn3r — DISMISSED** [review]

**Comment by c0repwn3r** [comment]
I’ll disable codestyle for this PR- give me a second

**Review by c0repwn3r — APPROVED** [review]

**Pull request merged**
